// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// deepClone
SEXP deepClone(SEXP obj);
RcppExport SEXP _jmvcore_deepClone(SEXP objSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj(objSEXP);
    rcpp_result_gen = Rcpp::wrap(deepClone(obj));
    return rcpp_result_gen;
END_RCPP
}
// repR6
SEXP repR6(SEXP obj, int n);
RcppExport SEXP _jmvcore_repR6(SEXP objSEXP, SEXP nSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type obj(objSEXP);
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    rcpp_result_gen = Rcpp::wrap(repR6(obj, n));
    return rcpp_result_gen;
END_RCPP
}
// swap
void swap(SEXP one, SEXP two);
RcppExport SEXP _jmvcore_swap(SEXP oneSEXP, SEXP twoSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< SEXP >::type one(oneSEXP);
    Rcpp::traits::input_parameter< SEXP >::type two(twoSEXP);
    swap(one, two);
    return R_NilValue;
END_RCPP
}
// set_priv
void set_priv(Rcpp::Environment r6, SEXP priv);
RcppExport SEXP _jmvcore_set_priv(SEXP r6SEXP, SEXP privSEXP) {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::Environment >::type r6(r6SEXP);
    Rcpp::traits::input_parameter< SEXP >::type priv(privSEXP);
    set_priv(r6, priv);
    return R_NilValue;
END_RCPP
}

RcppExport SEXP _rcpp_module_boot_R6List();
RcppExport SEXP _rcpp_module_boot_R6Utils();

static const R_CallMethodDef CallEntries[] = {
    {"_jmvcore_deepClone", (DL_FUNC) &_jmvcore_deepClone, 1},
    {"_jmvcore_repR6", (DL_FUNC) &_jmvcore_repR6, 2},
    {"_jmvcore_swap", (DL_FUNC) &_jmvcore_swap, 2},
    {"_jmvcore_set_priv", (DL_FUNC) &_jmvcore_set_priv, 2},
    {"_rcpp_module_boot_R6List", (DL_FUNC) &_rcpp_module_boot_R6List, 0},
    {"_rcpp_module_boot_R6Utils", (DL_FUNC) &_rcpp_module_boot_R6Utils, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_jmvcore(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
