# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deepClone <- function(obj) {
    .Call('_jmvcore_deepClone', PACKAGE = 'jmvcore', obj)
}

repR6 <- function(obj, n) {
    .Call('_jmvcore_repR6', PACKAGE = 'jmvcore', obj, n)
}

swap <- function(one, two) {
    invisible(.Call('_jmvcore_swap', PACKAGE = 'jmvcore', one, two))
}

set_priv <- function(r6, priv) {
    invisible(.Call('_jmvcore_set_priv', PACKAGE = 'jmvcore', r6, priv))
}

